### ISSUE TITLE
hi bro

### ISSUE THREAD

**Issue by Uniminin** [dantecpu/dantecpu#2]

**Comment by dantecpu** [comment]
You know there are no issues o.o

**Comment by Uniminin** [comment]
oof

**Comment by dantecpu** [comment]
o.o

**Comment by Uniminin** [comment]
broooooooo we want talk to you

**Comment by Uniminin** [comment]
find good messenger for chat

**Comment by Uniminin** [comment]
we left session and discord forever

**Comment by dantecpu** [comment]
> we left session and discord forever

nah

**Comment by dantecpu** [comment]
You just had your normal moment of doubt...

**Comment by Uniminin** [comment]
OKAPIA

**Comment by Uniminin** [comment]
introducing github chats 😃

**Comment by dantecpu** [comment]
Return teaching me English, I am not competent.

**Comment by dantecpu** [comment]
> introducing github chats 😃

lmao

**Comment by Uniminin** [comment]
oka im coming

**Comment by dantecpu** [comment]
> oka im coming

doubt, but if yes you are welcome as before
